___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [2]:
import numpy as np
import random

Вивести версію та конфігурацію бібліотеки:

In [36]:
print(np.__version__)
print(np.show_config())


1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/User/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/User/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/User/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\li

Створити вектор з 10 елементів, заповнений одиницями:

In [43]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Створити вектор із значеннями від 0 до 10:

In [7]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Створити матрицю 5 на 5, заповнену нулями:

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [86]:
z = np.random.randint(-10,10,20)
print(z)

nz = np.nonzero(z)
print(nz)

[ 9  2  5 -9  8  7 -2  1  9 -2 -9 -2  4  5  6  5  6 -2  1 -4]
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int64),)


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [87]:
mean_value = z.mean()
median_value = np.median(z)
std_value = np.std(z)

print('Cереднє значення:', mean_value)
print('Медіана:', median_value)
print('Cтандартне відхилення:', std_value)

Cереднє значення: 1.9
Медіана: 3.0
Cтандартне відхилення: 5.3188344587888805


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [22]:
matrix_1 = np.random.randint(-10,10,(4,2))
print('Матриця 1')
print(matrix_1)
print()

matrix_2 = np.random.randint(-10,10,(2,2))
print('Матриця 2')
print(matrix_2)
print()

prduct_matrix = np.dot(matrix_1,matrix_2)
print('Добуток')
print(prduct_matrix)

Матриця 1
[[ 2 -1]
 [-4 -1]
 [-1  6]
 [-6 -5]]

Матриця 2
[[-1 -5]
 [-9  8]]

Добуток
[[  7 -18]
 [ 13  12]
 [-53  53]
 [ 51 -10]]


Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [56]:
vector = np.reshape(prduct_matrix,(1,prduct_matrix.size))
print('Результуючу матрицю із попередньої задачі перетворити у вектор:', vector, sep='\n')
print()

v_min, v_max = vector.min(), vector.max()
print('Знайти мінімальне та максимальне значення:', v_min, v_max, sep='\n')
print()

vector[vector==v_max] = 0
print('Максимальне значення замінити на 0:',vector, sep='\n')

Результуючу матрицю із попередньої задачі перетворити у вектор:
[[  7 -18  13  12 -53   0   0 -10]]

Знайти мінімальне та максимальне значення:
-53
13

Максимальне значення замінити на 0:
[[  7 -18   0  12 -53   0   0 -10]]


Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [61]:
matrix_correlate = np.corrcoef(prduct_matrix)
print(matrix_correlate)

[[ 1. -1. -1.  1.]
 [-1.  1.  1. -1.]
 [-1.  1.  1. -1.]
 [ 1. -1. -1.  1.]]


Дано матрицю. Знайти ранг матриці:

In [66]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

matrix_rank = np.linalg.matrix_rank(a)
matrix_rank

3

Знайти визначник матриці:

In [71]:
det = np.linalg.det(a)
det

440.0000000000002

Знайти власні значення та власні вектори матриці: 

In [78]:
wa,va = np.linalg.eigh(a)
print('Власні значення матриці:', wa, sep='\n')
print()
print('Власні вектори матриці:', va, sep='\n')

Власні значення матриці:
[-14.30540864  -4.34740072  23.65280936]

Власні вектори матриці:
[[ 0.15315575  0.88160309  0.44645191]
 [ 0.63674998 -0.43353159  0.6376518 ]
 [-0.75570681 -0.18661821  0.62775861]]


Знайдіть число, що найчастіше зустрічається в масиві:

In [127]:
a = np.random.randint(0,10,50)
print(a)
print('Число, що найчастіше зустрічається в масиві:',np.bincount(a).argmax())

[1 3 4 9 4 8 6 8 7 5 7 5 8 0 0 3 5 6 8 1 2 5 6 2 4 0 9 2 0 4 0 9 7 2 2 0 9
 4 9 6 3 9 0 6 3 5 5 7 2 8]
Число, що найчастіше зустрічається в масиві: 0


Виведіть лише парні числа, що діляться на 5:

In [6]:
a = np.random.randint(0,10,50)
def p_even(lst):
    return [x for x in lst if x % 2 == 0 and x % 5 ==0]
print(a)
p_even(a)

b = a[(a%2==0)&(a%5==0)]
print(b)

[6 0 8 3 4 3 4 5 1 0 2 3 9 9 8 9 2 6 1 0 0 2 5 7 6 3 6 5 2 8 3 6 8 2 2 4 2
 8 7 5 8 4 9 5 1 0 4 5 5 8]
[0 0 0 0 0]


Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [3]:
a = np.array([[2, 5],[1, -10]])
b = np.array([1,3])

x = np.linalg.solve(a,b)
print(x)

[ 1.  -0.2]
